rest:
  fundamental_data_api:
    url: 'https://www.alphavantage.co/query?function=$function&symbol=$symbol&apikey=$key'
    key: JULI7BLT9T36YLN2
    requests_per_minute: 5
    requests_per_day: 500
  symbol_api:
    eodhistoricaldata:
      url: 'https://eodhistoricaldata.com/api/exchange-symbol-list/US?api_token=$key'
      key: '6234cff2ba7c31.29252804'
    alphavantage:
      url: 'https://www.alphavantage.co/query?function=LISTING_STATUS&apikey=$key'
      key: JULI7BLT9T36YLN2

db:
  database_url: 'mongodb://localhost:27017/'
  database: mydatabase
